---
- name: Pull Docker Image of Calculator
  hosts: local
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Pull image
      docker_image:
        name: todorokishotoua15/calculator:latest
        source: pull
    - name: Start docker service
      service:
        name: docker
        state: started
    - name: Removing calc container
      docker_container:
        name: calc
        state: absent

    - name: Running container
      shell: docker run -it -d --name calc todorokishotoua15/calculator