---
- name: Pull Docker Image of Calculator
  hosts: local
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Pull image
      docker_image:
        name: todorokishotoua15/calc:latest
        source: pull
    - name: Start docker service
      service:
        name: docker
        state: started
    - name: Stop docker containers
      shell: 
        docker stop calc
        docker rmi todorokishotoua15/calc

    - name: Running container
      shell: docker run -it -d --name calc todorokishotoua15/calc